language: python
env:
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.5
 - DJANGO_VERSION=1.6
python:
 - "2.6"
 - "2.7"
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
script: ./run.sh test
matrix:
  include:
    - python: 3.3
      env: DJANGO_VERSION=1.5
    - python: 3.3
      env: DJANGO_VERSION=1.6
